# -*- coding: utf-8 -*-
"""Swapnonil_AI_ML_Week1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qA9a5y9xLJdjbba_xxe8jKKWaqTV_RBi

Task 1: Python Basics & Operators
1. Create a Python script that accepts two numbers from the user.
2. Perform all basic arithmetic operations (add, subtract, multiply, divide, modulus, power).
3. Demonstrate use of comparison and logical operators (>, <, ==, !=, and, or, not).
4. Print results clearly using formatted output (f-strings).
"""

import random
import numpy as np
from datetime import datetime

# Task 1: Python Basics & Operators
num1 = float(input("Enter first number: "))
num2 = float(input("Enter second number: "))

print(f"Addition: {num1 + num2}")
print(f"Subtraction: {num1 - num2}")
print(f"Multiplication: {num1 * num2}")
print(f"Division: {num1 / num2}")
print(f"Modulus: {num1 % num2}")
print(f"Power: {num1 ** num2}")

print(f"{num1} > {num2}: {num1 > num2}")
print(f"{num1} < {num2}: {num1 < num2}")
print(f"{num1} == {num2}: {num1 == num2}")
print(f"{num1} != {num2}: {num1 != num2}")

"""Task 2: Lists and Arrays
1. Create a list of 10 random integers.
2. Perform the following operations:
○ Add and remove elements.
○ Find the maximum and minimum values.
○ Sort the list.
3. Convert the list into a NumPy array and calculate:
○ Mean, Median, and Standard Deviation.
"""

# Task 2: Lists and Arrays
import random
import numpy as np
from datetime import datetime
numbers = [random.randint(1, 100) for _ in range(10)]
numbers.append(50)
numbers.pop(0)

print("List:", numbers)
print("Max:", max(numbers))
print("Min:", min(numbers))

array = np.array(numbers)
print("Mean:", np.mean(array))
print("Median:", np.median(array))
print("Std Dev:", np.std(array))

"""Task 3: Dictionaries and Sets
1. Create a dictionary named student with keys: name, course, marks.
2. Add a new key grade and assign a value based on marks (e.g., A/B/C).
3. Print all keys and values using a loop.
4. Create two sets of AI tools,
"""

# Task 3: Dictionary & Sets
import random
import numpy as np
from datetime import datetime
student = {"name": "Swapnonil", "course": "AI/ML", "marks": 82}

if student["marks"] >= 80:
    student["grade"] = "A"
elif student["marks"] >= 60:
    student["grade"] = "B"
else:
    student["grade"] = "C"

for k, v in student.items():
    print(k, ":", v)

ai_tools_1 = {"ChatGPT", "TensorFlow", "PyTorch"}
ai_tools_2 = {"PyTorch", "Keras", "Scikit-learn"}
print("Common AI Tools:", ai_tools_1 & ai_tools_2)

"""Task 4: File Handling
1. Create a text file named ai_students.txt.
2. Write details of at least 5 students (name, marks, grade).
3. Read the file and display students who scored above 75 marks.
"""

# Task 4: File Handling
import random
import numpy as np
from datetime import datetime
with open("ai_students.txt", "w") as f:
    f.write("Amit, 78, B\nSneha, 85, A\nRahul, 72, B\nPriya, 90, A\nKaran, 65, B\n")

with open("ai_students.txt", "r") as f:
    for line in f:
        name, marks, grade = line.strip().split(", ")
        if int(marks) > 75:
            print("Above 75:", name)

"""Task 5: Real-World Mini Project
Create a Python program named ai_prompt_logger.py that:
1. Accepts a user input (simulating an AI prompt).
2. Saves the prompt text in a file named prompt_history.txt.
3. Each time you run the program, new prompts are appended with timestamps.
"""

# Task 5: Prompt Logger
prompt = input("Enter AI prompt: ")
timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

with open("prompt_history.txt", "a") as f:
    f.write(f"[{timestamp}] {prompt}\n")

print("Prompt saved!")