# -*- coding: utf-8 -*-
"""MySQL_Assignment_Week_2.ipynb.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zo4AaIRycF3-rDNARHzwtJ4klGci5Vvl

# MySQL Assignment

**Name:** Swapnonil Banerjee  
**Database Name:** college_db  

This assignment demonstrates creation of tables and SQL operations
using WHERE, AND, OR, NOT, ORDER BY and LIKE.
"""

CREATE DATABASE college_db;
USE college_db;

CREATE TABLE Students(
    student_id INT PRIMARY KEY,
    name VARCHAR(50),
    age INT,
    city VARCHAR(50)
);

CREATE TABLE Courses(
    course_id INT PRIMARY KEY,
    course_name VARCHAR(50),
    duration INT
);

INSERT INTO Students VALUES
(1, 'Amit', 21, 'Mumbai'),
(2, 'Neha', 22, 'Pune'),
(3, 'Rohit', 20, 'Delhi'),
(4, 'Nisha', 23, 'Mumbai');

INSERT INTO Courses VALUES
(101, 'Data Science', 6),
(102, 'Web Development', 4),
(103, 'AI and ML', 8);

-- WHERE with AND
SELECT * FROM Students
WHERE age > 21 AND city = 'Mumbai';

-- WHERE with OR
SELECT * FROM Students
WHERE city = 'Mumbai' OR city = 'Pune';

-- WHERE with NOT
SELECT * FROM Students
WHERE NOT city = 'Delhi';

-- ORDER BY
SELECT * FROM Students
ORDER BY age ASC;

-- LIKE Operator
SELECT * FROM Students
WHERE name LIKE 'N%';